name: copernicus-marine
channels:
  - conda-forge
dependencies:
  - python
  - basemap
  - basemap-data-hires
  - cartopy
  - dask-core
  - fiona
  - ftputil
  - libnetcdf>=4.6.1
  - matplotlib
  - moviepy
  - natsort
  - netcdf4>=1.4.2
  - netcdf-fortran>=4.4.4
  - numpy
  - pandas
  - pip
  - requests
  - scipy
  - seaborn
  - xarray
  - pip:
    - jupyter-server-proxy
    - jupyter-offlinenotebook
    - motuclient>=1.8.4
