#!/bin/bash

jupyter labextension install jupyter-offlinenotebook

wget -q -O notebook-gallery-diving.tar.gz https://atlas.mercator-ocean.fr/s/zgsbEMgwXLmjoxZ/download
tar -zxvf notebook-gallery-diving.tar.gz
rm -rf notebook-gallery-diving.tar.gz

jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace NOTEBOOK-GALLERY-DIVING/*.ipynb
