#!/bin/bash

jupyter labextension install jupyter-offlinenotebook

wget -q -O operational-satellite-oceanography-training-20210528.zip https://atlas.mercator-ocean.fr/s/sC7DRSAWKHsTkFZ/download
unzip operational-satellite-oceanography-training-20210528.zip
tar -xvf DIVE-Part4/DIVE-Part4-assimilating_altimetry_in_a_3D_model.tar.gz
rm -rf DIVE-Part4 && rm -rf operational-satellite-oceanography-training-20210528.gzip

jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace DIVE-Part4-assimilating_altimetry_in_a_3D_model/*.ipynb
